name: Inject State into LocalStack using Cloud Pod

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  infrastructure-check:
    name: Setup infrastructure using Cloud Pod
    runs-on: ubuntu-latest
    env:
      LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install lstk
        run: |
          npm install -g @localstack/lstk

      - name: Start LocalStack
        run: |
          docker pull localstack/localstack:latest
          # Start LocalStack in the background
          LOCALSTACK_LS_LOG=trace lstk start

      - name: Inject Cloud Pod
        run: |
          lstk snapshot load pod:terraform-shipment-pod

      - name: Check for Bucket
        run: |
          lstk setup aws --non-interactive --force
          output=$(lstk aws s3api list-buckets --query "Buckets[?contains(Name, 'shipment-picture-bucket')].Name" --output text)
          if [ -z "$output" ]; then
            echo "Created bucket not found."
            exit 1
          else echo "Bucket with random name was found: $output"
          fi

      - name: Generate a Diagnostic Report
        if: failure()
        run: |
          curl -s localhost:4566/_localstack/diagnose | gzip -cf > diagnose.json.gz

      - name: Upload the Diagnostic Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose.json.gz
          path: ./diagnose.json.gz
